version: "3.8"

services:
  movieapp-db:
    image: postgres:13
    restart: always
    container_name: "movieapp-db"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: finki123.
      POSTGRES_DB: Kinoo
    ports:
      - "5434:5432"
    volumes:
      - ./db-postgres/postgres-data:/var/lib/postgresql/data
      - ./db-postgres/create.sql:/docker-entrypoint-initdb.d/create.sql
    networks:
      - movieapp-net

  movieapp:
    image: "movieapp-image:latest"
    container_name: movieapp
    environment:
      SPRING_APPLICATION_JSON: '{
             "spring.datasource.url"  : "jdbc:postgresql://movieapp-db:5432/Kinoo",
             "spring.datasource.username" : "postgres",
             "spring.datasource.password" : "finki123.",
             "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.PostgreSQLDialect",
             "spring.jpa.hibernate.ddl-auto" : "validate",
             "spring.datasource.hikari.connectionTimeout" : "20000",
             "spring.datasource.hikari.maximumPoolSize" : "5",
             "spring.jpa.show-sql" : "true"
           }'
    depends_on:
      - movieapp-db
    ports:
      - "9090:9090"
    networks:
      - movieapp-net

networks:
  movieapp-net:
    driver: bridge

volumes:
  movieapp-data:
