name: Build and Push

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build and package with Maven
        run: mvn clean install -DskipTests

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v3
        with:
          path: target/*.jar
        if: success()

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/movieapp-image:latest .

      - name: Push Docker image to DockerHub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/movieapp-image:latest

      - name: Run Docker container
        run: |
          docker run -d -p 9090:9090 ${{ secrets.DOCKER_USERNAME }}/movieapp-image:latest

      - name: Display Docker logs on failure
        if: failure()
        run: |
          docker logs $(docker ps -a -q --filter ancestor=${{ secrets.DOCKER_USERNAME }}/movieapp-image:latest)
